# fly.toml app configuration file generated for lithium on 2026-04-14T13:34:33-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lithium'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '512mb'
  cpus = 2
  memory_mb = 512
